### ISSUE TITLE
Support Custom Endpoints and LLM Providers

### ISSUE THREAD

**Issue by lemig** [kestra-io/plugin-openai#40]
### Feature description

**Summary**  
Currently, the plugin only supports using the default OpenAI endpoints through the OpenAI client. However, the OpenAI Python library can also be used against alternate LLM endpoints, such as LM Studio or vLLM, which are compatible with the OpenAI API. It would be very helpful to allow users of this plugin to specify a custom endpoint/URL and other configuration parameters, enabling the plugin to work with different LLM backends.

**Request**  
Expose a configuration option in the plugin to define a custom API base URL. 

**Use Case**  
- Users who host their own LLM servers using open-source projects (e.g., LM Studio, vLLM, LiteLLM) but still want to leverage Kestra’s workflow automation.  
- Scenarios where data privacy constraints prevent using the public OpenAI service.  

**Benefit**  
This flexibility would allow more developers to adopt and contribute to the plugin by using it with any LLM backend that supports the OpenAI API interface.

**Comment by jrsperry** [comment]
i'd add that a bunch of other LLM providers/hosters also have openai compliant apis. Groq, TogetherAI are just a couple. This should just be a matter of allowing the "base_url" to be configurable.  

Here's a link to groq for example: https://console.groq.com/docs/openai

**Comment by Hurricane31337** [comment]
I second this request. It would help us greatly if we could use our local vLLM hosted models via the OpenAI plugin. The Ollama API is not standard-compliant and Ollama isn't as great as vLLM, SGLang etc. for hosting for more than 20 users.

**Comment by anna-geller** [comment]
I recommend using the AI Agent plugin with either OpenAI or OpenRouter as provider. OpenAI provider has baseUrl property here already:

```yaml
id: analytics_agent
namespace: company.ai

inputs:
  - id: data
    type: JSON
    defaults: |
      [
        {"region": "North America", "sales": 120000, "month": "September"},
        {"region": "Europe", "sales": 95000, "month": "September"},
        {"region": "Asia", "sales": 143000, "month": "September"}
      ]

tasks:
  - id: agent
    type: io.kestra.plugin.ai.agent.AIAgent
    provider:
      type: io.kestra.plugin.ai.provider.OpenAI
      baseUrl: https://openrouter.ai/api/v1
      apiKey: "{{ kv('OPENROUTER_API_KEY') }}"
      modelName: x-ai/grok-4 # pick any https://openrouter.ai/models
    systemMessage: You are an expert data analyst. Extract insights based on the provided data.
    prompt: "Analyze the following dataset: {{ inputs.data }}"
```

or:
```yaml
id: analytics_agent
namespace: company.ai

inputs:
  - id: data
    type: JSON
    defaults: |
      [
        {"region": "North America", "sales": 120000, "month": "September"},
        {"region": "Europe", "sales": 95000, "month": "September"},
        {"region": "Asia", "sales": 143000, "month": "September"}
      ]

tasks:
  - id: agent
    type: io.kestra.plugin.ai.agent.AIAgent
    provider:
      type: io.kestra.plugin.ai.provider.OpenRouter
      baseUrl: https://openrouter.ai/api/v1
      apiKey: "{{ kv('OPENROUTER_API_KEY') }}"
      modelName: x-ai/grok-4 # pick any https://openrouter.ai/models
    systemMessage: You are an expert data analyst. Extract insights based on the provided data.
    prompt: "Analyze the following dataset: {{ inputs.data }}"
```
