### ISSUE TITLE
Add Structured Outputs `response_format` for ChatCompletion Task

### ISSUE THREAD

**Issue by lemig** [kestra-io/plugin-openai#41]
### Feature description

**Summary**  
OpenAI has a beta feature that returns structured responses according to a user-defined JSON schema. This requires special handling in the client call (e.g., using `client.beta.chat.completions.parse`). The plugin does not currently allow specifying or validating a JSON schema for structured outputs, and it does not yet hook into the beta endpoint.

**Request**  
1. Add support for passing a JSON schema (or similar structure) to the OpenAI request.  
2. Update the plugin to call the beta endpoint (e.g., `client.beta.chat.completions.parse`) when a JSON schema is present.  
3. Provide a way to parse, validate, or transform the LLM response into JSON that matches the specified schema.  

**Use Case**  
- Generate responses that must adhere to a strict format (e.g., generating structured data for subsequent steps in a workflow).  
- Validate returned data against a schema in order to ensure correctness and make programmatic consumption straightforward.  

**Benefit**  
By letting the user provide a schema for the LLM output and leveraging the beta endpoint’s structured response feature, Kestra users can reliably integrate LLM responses into automated pipelines with more predictability and less post-processing.

**Comment by Hurricane31337** [comment]
This is even avaliable on vLLM and other local LLM inference platforms already. You can build really awesome things with it, especially in the Kestra environment where you probably want an LLM take a look at a log output and convert it to a clearly understandable result for the like UI for example:

```json
{
   "success" : false,
   "most_relevant_error" : "Error connecting to the SQLite database."
}
```

**Comment by wrussell1999** [comment]
We have support for Structured Output with the Responses Task. However, we don't have the `response_format` property for ChatCompletions. It might be possible using function calling: https://openai.com/index/introducing-structured-outputs-in-the-api/

See this example below for Responses:
```yaml
id: structured_output_demo
namespace: company.team

inputs:
  - id: food
    type: STRING
    defaults: Avocado

tasks:
  - id: generate_structured_response
    type: io.kestra.plugin.openai.Responses
    apiKey: "{{ secret('OPENAI_API_KEY') }}"
    model: gpt-4.1-mini
    input: "Fill in nutrients information for the following food: {{ inputs.food }}"
    text:
      format:
        type: json_schema
        name: food_macronutrients
        schema:
          type: object
          properties:
            food:
              type: string
              description: The name of the food or meal.
            macronutrients:
              type: object
              description: Macro-nutritional content of the food.
              properties:
                carbohydrates:
                  type: number
                  description: Amount of carbohydrates in grams.
                proteins:
                  type: number
                  description: Amount of proteins in grams.
                fats:
                  type: number
                  description: Amount of fats in grams.
              required:
                - carbohydrates
                - proteins
                - fats
              additionalProperties: false
            vitamins:
              type: object
              description: Specific vitamins present in the food.
              properties:
                vitamin_a:
                  type: number
                  description: Amount of Vitamin A in micrograms.
                vitamin_c:
                  type: number
                  description: Amount of Vitamin C in milligrams.
                vitamin_d:
                  type: number
                  description: Amount of Vitamin D in micrograms.
                vitamin_e:
                  type: number
                  description: Amount of Vitamin E in milligrams.
                vitamin_k:
                  type: number
                  description: Amount of Vitamin K in micrograms.
              required:
                - vitamin_a
                - vitamin_c
                - vitamin_d
                - vitamin_e
                - vitamin_k
              additionalProperties: false
          required:
            - food
```
