### ISSUE TITLE
Add a new OpenAI UploadFile task

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-openai#44]
### Feature description

New task to interact with https://platform.openai.com/docs/api-reference/files

It should output the `fileId`.

```yaml
id: files_api
namespace: company.team

inputs:
  - id: myfile
    type: FILE

tasks:
  - id: upload
    type: io.kestra.plugin.openai.UploadFile
    apiKey: "yourOpenAIapiKey"
    file: "{{ inputs.myfile }}"
    purpose: search
    description: |
      Uploads a file provided from internal storage via a FILE type input to the /v1/files API endpoint.The response fileId is extracted and made available for subsequent tasks.
```

The purpose of this task is to enable using files in the future `Responses` task, e.g.: [link](https://platform.openai.com/docs/guides/pdf-files?api-mode=responses#uploading-files)

```yaml
curl https://api.openai.com/v1/files \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -F purpose="user_data" \
    -F file="@draconomicon.pdf"

curl "https://api.openai.com/v1/responses" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -d '{
        "model": "gpt-4.1",
        "input": [
            {
                "role": "user",
                "content": [
                    {
                        "type": "input_file",
                        "file_id": "file-6F2ksmvXxt4VdoqmHRw6kL"
                    },
                    {
                        "type": "input_text",
                        "text": "What is the first dragon in the book?"
                    }
                ]
            }
        ]
    }'
```

The official SDK should support that /v1/files endpoint:

```Java
import com.openai.models.files.FileCreateParams;
import com.openai.models.files.FileObject;
import com.openai.models.files.FilePurpose;
import java.nio.file.Paths;

// Build the upload parameters – adjust "purpose" as needed (e.g., "search" or "fineTune")
FileCreateParams params = FileCreateParams.builder()
    .purpose(FilePurpose.SEARCH) // or FilePurpose.FINE_TUNE, etc.
    .file(Paths.get("myfile.txt"))
    .build();

// Upload the file
FileObject fileObject = client.files().create(params);

// Retrieve the file ID for later use
String fileId = fileObject.getId();
```
