### ISSUE TITLE
Add OpenAI Responses task

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-openai#45]
### Feature description

To leverage the new Responses API -- see [OpenAI API](https://platform.openai.com/docs/api-reference/responses) i.e. `POST https://api.openai.com/v1/responses`, including built-in tools (e.g. web search, function calling), persistence, and structured outputs, we can add a new task: `io.kestra.plugin.openai.Responses`. 

**Task parameters:**

- `apiKey` (STRING, required): OpenAI API key, best to pass as a secret
- `model` (STRING, required): model name (e.g., `gpt-4o`).
- `input` (STRING or ARRAY, required): a single user prompt or an array of message objects (for multi-turn or multimodal).
- `text` (OBJECT, optional): Configuration options for a text response from the model in YAML 
- `tools` (ARRAY, optional): list of built-in tools to enable (e.g., `web_search`, `file_search`, `computer_use`).
- `toolChoice` (STRING, optional): Controls which (if any) tool is called by the model. `none` means the model will not call any tool and instead generates a message. `auto` means the model can pick between generating a message or calling one or more tools. `required` means the model must call one or more tools.
- `store` (BOOLEAN, optional): If true (default), persists response and chat history within OpenAI’s storage; if false, disables storage.
- `previousResponseId` (STRING, optional): to continue a previous conversation with context.
- `reasoning` (OBJECT or null, optional):
    - `effort` (STRING, optional): constrains effort on reasoning for [reasoning models](https://platform.openai.com/docs/guides/reasoning). Currently supported values are `low`, `medium`, and `high`.
    - `generateSummary` (STRING, optional): A summary of the reasoning performed by the model. This can be useful for debugging and understanding the model's reasoning process. One of `concise` or `detailed`.
- Less frequently used optional properties 
    - `maxOutputTokens` (INTEGER, optional): maximum tokens in the response.
    - `temperature` (FLOAT, optional): sampling temperature (0-2)
    - `topP` (FLOAT, optional): nucleus sampling parameter (0-1).
    - `parallelToolCalls` (BOOLEAN, optional): Allow parallel tool execution.

**Outputs:**

- `outputText` (STRING): the generated text. (SDK-only)
- `responseId` (STRING): ID of the persisted response.
- `sources` (ARRAY, optional): list of sources (for web/file search).
- `rawResponse` (OBJECT): full API response for advanced use.

## Use cases + example flows

- Text input: simple text input and text output, no tools
    
    ```yaml
    id: responses_text
    namespace: company.team
    
    inputs:
      - id: prompt
        type: STRING
        defaults: Explain what is Kestra in 3 sentences
    
    tasks:
      - id: explain
        type: io.kestra.plugin.openai.Responses
        apiKey: "{{ secret('OPENAI_API_KEY') }}"
        model: gpt-4.1
        input: "{{ inputs.prompt }}"
    
      - id: log
        type: io.kestra.plugin.core.log.Log
        message: "{{ outputs.explain.outputText }}"
    ```
    
- Image input: Transcribe text from images, either from web or from internal storage
    
    ```yaml
    id: responses_image
    namespace: company.team
    
    inputs:
      - id: user_prompt
        type: STRING
        defaults: Transcribe text from the image
      - id: image
        type: FILE
    
    tasks:
      - id: image_from_web
        type: io.kestra.plugin.openai.Responses
        apiKey: "{{ secret('OPENAI_API_KEY') }}"
        model: gpt-4.1
        input:
          - role: user
            content:
              - type: input_text
                text: "{{ inputs.user_prompt }}"
              - type: input_image
                image_url: https://kestra.io/blogs/orchestrations-differences.jpg
    
      - id: image_from_internal_storage
        type: io.kestra.plugin.openai.Responses
        apiKey: "{{ secret('OPENAI_API_KEY') }}"
        model: gpt-4.1
        input:
          - role: user
            content:
              - type: input_text
                text: "{{ inputs.user_prompt }}"
              - type: input_image
                image_url: "{{ inputs.image }}" # under the hood, the plugin needs to base64-encode the image https://platform.openai.com/docs/guides/images?api-mode=responses&format=base64-encoded
    ```
    
- Web search: fetch news
    
    ```yaml
    id: responses_web_search
    namespace: company.team
    
    inputs:
      - id: prompt
        type: STRING
        defaults: What was a positive news story from today?
    
    tasks:
      - id: news
        type: io.kestra.plugin.openai.Responses
        apiKey: "{{ secret('OPENAI_API_KEY') }}"
        model: gpt-4.1
        input: "{{ inputs.prompt }}"
        toolChoice: required
        tools:
          - type: web_search_preview  # only type string is required
            search_context_size: low  # optional; low, medium, high
            user_location:
              type: approximate
              country: FR
    
      - id: log
        type: io.kestra.plugin.core.log.Log
        message: "{{ outputs.story.outputText }}"
    ```
    

![Image](https://github.com/user-attachments/assets/9fc5bf32-e6d1-451c-8f9c-5db3903f331e)

    
- PDF file input: chat with PDF
    - Alternatively, we may upload a PDF using the [Files API](https://platform.openai.com/docs/api-reference/files), then reference its file ID in an API request to the model: https://github.com/kestra-io/plugin-openai/issues/44
        
        ```bash
        curl https://api.openai.com/v1/files \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -F purpose="user_data" \
            -F file="@draconomicon.pdf"
        
        curl "https://api.openai.com/v1/responses" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -d '{
                "model": "gpt-4.1",
                "input": [
                    {
                        "role": "user",
                        "content": [
                            {
                                "type": "input_file",
                                "file_id": "file-6F2ksmvXxt4VdoqmHRw6kL"
                            },
                            {
                                "type": "input_text",
                                "text": "What is the first dragon in the book?"
                            }
                        ]
                    }
                ]
            }'
        ```
        
    
    ```yaml
    id: responses_pdf
    namespace: company.team
    
    tasks:
      - id: get
        type: io.kestra.plugin.core.http.Download
        uri: https://huggingface.co/datasets/kestra/datasets/resolve/main/pdf/app_store.pdf
    
      - id: pdf_upload
        type: io.kestra.plugin.openai.UploadFile
        apiKey: "{{ secret('OPENAI_API_KEY') }}"
        file: "{{ outputs.get.uri }}"
        purpose: search
    
      - id: pdf_from_openai
        type: io.kestra.plugin.openai.Responses
        apiKey: "{{ secret('OPENAI_API_KEY') }}"
        model: gpt-4.1
        input:
          - role: user
            content:
              - type: input_file
                file_id: "{{ outputs.pdf_upload.fileId }}"
              - type: input_text
                text: Transcribe text from the PDF file
    
      - id: pdf_from_internal_storage
        type: io.kestra.plugin.openai.Responses
        apiKey: "{{ secret('OPENAI_API_KEY') }}"
        model: gpt-4.1
        input:
          - role: user
            content:
              - type: input_file
                filename: app_store.pdf
                file_data: "{{ outputs.get.uri }}" # under the hood, the plugin needs to base64-encode the PDF file https://platform.openai.com/docs/guides/pdf-files?api-mode=responses#base64-encoded-files
              - type: input_text
                text: Transcribe text from the PDF file
    ```
    
- Functions: prioritize request
    
    ```yaml
    id: responses_functions
    namespace: company.team
    
    inputs:
      - id: prompt
        type: STRING
        defaults: I love your product and would purchase it again!
    
    tasks:
      - id: prioritize_response
        type: io.kestra.plugin.openai.Responses
        apiKey: "{{ secret('OPENAI_API_KEY') }}"
        model: gpt-4.1
        input: "{{ inputs.prompt }}"
        toolChoice: auto
        tools:
          - type: function
            name: respond_to_review
            description: >-
              Given the customer product review provided as input, determine how
              urgently a reply is required and then provide suggested response text.
            strict: true
            parameters:
              type: object
              required:
                - response_urgency
                - response_text
              properties:
                response_urgency:
                  type: string
                  description: >-
                    How urgently this customer review needs a reply. Bad reviews must
                    be addressed immediately before anyone sees them. Good reviews
                    can wait until later.
                  enum:
                    - reply_immediately
                    - reply_later
                response_text:
                  type: string
                  description: The text to post online in response to this review.
              additionalProperties: false
    ```
    
- Conversation state: stateful chat
    
    ```yaml
    id: chat_stateful
    namespace: company.team
    
    inputs:
      - id: user_input
        type: STRING
        default: How can I get started with Kestra?
        
      - id: reset_conversation
        type: BOOLEAN
        default: false
    
    tasks:
      - id: maybe_reset_conversation
        runIf: "{{ inputs.reset_conversation }}"
        type: io.kestra.plugin.kv.Delete
        key: "RESPONSE_ID"
    
      - id: chat_request
        type: io.kestra.plugin.openai.Responses
        apiKey: "{{ secret('OPENAI_API_KEY') }}"
        model: gpt-4.1
        previousResponseId: "{{ kv('RESPONSE_ID', errorOnMissing=false) }}"
        input:
          - role: user
            content:
              - type: input_text
                text: "{{ inputs.user_input }}"
    
      - id: store_response
        type: io.kestra.plugin.kv.Set
        key: "RESPONSE_ID"
        value: "{{ outputs.chat_request.responseId }}"
    
      - id: output_log
        type: io.kestra.plugin.core.log.Log
        message: "Response: {{ outputs.chat_request.outputText }}"
    
    ```
    
- Structured `json_object`: search web and return structured JSON
    
    In contrast to `json_schema`, JSON mode (format `json_object`) is a more basic version of the Structured Outputs feature. While JSON mode ensures that model output is valid JSON, Structured Outputs reliably matches the model's output to the schema you specify.
    
    ```yaml
    id: responses_json_object
    namespace: company.team
    
    inputs:
      - id: prompt
        type: STRING
        defaults: "List recent trends in workflow orchestration. Return as JSON with fields: trend, description, benefits, risks, limitations."
    
    tasks:
      - id: news
        type: io.kestra.plugin.openai.Responses
        apiKey: "{{ secret('OPENAI_API_KEY') }}"
        model: gpt-4.1
        input: "{{ inputs.prompt }}"
        text:
          format:
            type: json_object
        toolChoice: required
        tools:
          - type: web_search_preview
    
      - id: log
        type: io.kestra.plugin.core.log.Log
        message: "{{ outputs.story.outputText }}"
    ```
    
- Structured `json_schema`: extract nutrients from a given food
    
    ```yaml
    id: responses_json_object_example
    namespace: company.team
    
    inputs:
      - id: food
        type: STRING
        default: Avocado
    
    tasks:
      - id: generate_structured_response
        type: io.kestra.plugin.openai.Responses
        apiKey: "{{ secret('OPENAI_API_KEY') }}"
        model: gpt-4.1
        input: "Extract nutrients from the following food: {{ inputs.food }}"
        text:
          format:
            type: json_schema
            name: food_macronutrients
            schema:
              type: object
              properties:
                food:
                  type: string
                  description: The name of the food or meal.
                macronutrients:
                  type: object
                  description: Macro-nutritional content of the food.
                  properties:
                    carbohydrates:
                      type: number
                      description: Amount of carbohydrates in grams.
                    proteins:
                      type: number
                      description: Amount of proteins in grams.
                    fats:
                      type: number
                      description: Amount of fats in grams.
                  required:
                    - carbohydrates
                    - proteins
                    - fats
                  additionalProperties: false
                vitamins:
                  type: object
                  description: Specific vitamins present in the food.
                  properties:
                    vitamin_a:
                      type: number
                      description: Amount of Vitamin A in micrograms.
                    vitamin_c:
                      type: number
                      description: Amount of Vitamin C in milligrams.
                    vitamin_d:
                      type: number
                      description: Amount of Vitamin D in micrograms.
                    vitamin_e:
                      type: number
                      description: Amount of Vitamin E in milligrams.
                    vitamin_k:
                      type: number
                      description: Amount of Vitamin K in micrograms.
                  required:
                    - vitamin_a
                    - vitamin_c
                    - vitamin_d
                    - vitamin_e
                    - vitamin_k
                  additionalProperties: false
              required:
                - food
    ```
    

## **Implementation Notes**

- OpenAI’s REST API endpoints for `/v1/responses`
    - https://platform.openai.com/docs/api-reference/responses
    - https://platform.openai.com/docs/guides/responses-vs-chat-completions
    - Official Java SDK already includes Responses API https://github.com/openai/openai-java
- Keep existing ChatCompletion tasks to avoid BC — https://kestra.io/plugins/plugin-openai
