### ISSUE TITLE
The Responses task doesn't work with image content

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-openai#51]
### Describe the issue

`You must provide 'mimeType' as an additional parameter, when using a file from 'input: FILE'
2025-05-16 11:25:25.584java.lang.IllegalArgumentException: You must provide 'mimeType' as an additional parameter, when using a file from 'input: FILE'
	at io.kestra.plugin.openai.utils.ParametersUtils.processImageContent(ParametersUtils.java:112)`

Both passing input from inputs + output of the previous task don't work. Repro:

```yaml
id: responses_image
namespace: company.team

inputs:
  - id: user_prompt
    type: STRING
    defaults: Transcribe text from the image

  - id: image
    type: FILE

tasks:
  - id: download
    type: io.kestra.plugin.core.http.Download
    uri: https://kestra.io/blogs/orchestrations-differences.jpg

  - id: image_from_web
    type: io.kestra.plugin.openai.Responses
    apiKey: "{{ kv('OPENAI_API_KEY') }}"
    model: gpt-4.1-mini
    input:
      - role: user
        content:
          - type: input_text
            text: "{{ inputs.user_prompt }}"
          - type: input_image
            image_url: "{{ outputs.download.uri }}"

  - id: image_from_internal_storage
    type: io.kestra.plugin.openai.Responses
    apiKey: "{{ kv('OPENAI_API_KEY') }}"
    model: gpt-4.1-mini
    input:
      - role: user
        content:
          - type: input_text
            text: "{{ inputs.user_prompt }}"
          - type: input_image
            image_url: "{{ inputs.image }}"
```

### Environment

- Kestra Version: develop
